### ISSUE TITLE
DS418 - DSM 7.2.1-69057 Update 5 - failed to install package container manager 

### ISSUE THREAD

**Issue by Alyalkar** [007revad/ContainerManager_for_all_armv8#23]
Hello, 

I recently followed your tutorial for my **DS418play**, but with **DSM 7.2.1-69057 Update 5**. I see in your tutorial that it is tested on update 4 but not on 5. I tested to install on update 5 but it did not work correctly. It give me the message "failed to install package container manager" when I install manually the package. Do you know if there is a possibility to bypass ?

![image](https://github.com/user-attachments/assets/c38c00ff-24a6-4181-b58e-512da2fb0d97)

Otherwise, thank you for the tutorial. It being a long time that I search this. 

Thank you

**Comment by Alyalkar** [comment]
I fixed my problem by myself. Here is the solution that fixed my problem, if it could help anyone. I read on a forum that deleting the docker and @docker folders should unblock the package installation. So, I deleted this 2 folders on the /volume and when i retried the script make the installation correctly. I disabled next the auto update and that's it. It work fine now.
Thanks

**Comment by 007revad** [comment]
How did your DS418 already have `docker` and `@docker` folders?

**Comment by Alyalkar** [comment]
I tried before several times and I think it create folders maybe, but I don't really know how.
