### ISSUE TITLE
Synology seems to have protected their OS : install possible but after script ended, error

### ISSUE THREAD

**Issue by droumanet** [007revad/ContainerManager_for_all_armv8#28]
All seems to install correctly, but when the script `install_container_manager.sh` end, an update is needed on Workstation. Then, Container manager went down.
'Please reinstall the package because something went wrong'

Here is the message (french) screenshot:
![image](https://github.com/user-attachments/assets/279dc705-de6f-4631-be7c-5e168f5ce17d)

**Comment by 007revad** [comment]
Which DSM version? Which Synology model?

What do these commands return?
```
sudo synogetkeyvalue /var/packages/ContainerManager/INFO version
sudo synogetkeyvalue /var/packages/ContainerManager/INFO arch
sudo synogetkeyvalue /var/packages/ContainerManager/INFO exclude_model
```

**Comment by droumanet** [comment]
DS218 play
/INFO version : 20.10.23-1437
/INFO arch : armv8
/INFO exclude_model : synology_rtd1296_ds118 synology_rtd1296_ds218 synology_rtd1296_ds218play synology_rtd1296_ds418 synology_rtd1296_ds418j synology_armada37xx_ds119j synology_rtd1296_rs819
![image](https://github.com/user-attachments/assets/01688bc0-7db7-45d4-8b37-9183f4bf610a)

**Comment by 007revad** [comment]
This should fix it:
```
sudo sed -i "/exclude_model=*/d" /var/packages/ContainerManager/INFO
```

**Comment by droumanet** [comment]
It's fixed.
Thanks a lot !
![image](https://github.com/user-attachments/assets/585864ea-67f9-4748-b0b9-201dd58470af)

**Comment by droumanet** [comment]
It's fixed, thanks a lot !!!
![image](https://github.com/user-attachments/assets/9319ae37-1ed8-4ca0-8b40-a87b9d17eeb8)

**Comment by fvatter** [comment]
I have same issue, can u help me please?

![Image](https://github.com/user-attachments/assets/ab4bf125-878f-4481-b2fa-6eb7b92e1ab2)

![Image](https://github.com/user-attachments/assets/c2ea28cf-9afc-4479-8999-d15204cfcd22)

![Image](https://github.com/user-attachments/assets/6d5a30ab-6804-4522-81d8-d1a278fbd36c)

**Comment by fvatter** [comment]
this command dont work for me

sudo synogetkeyvalue /var/packages/ContainerManager/INFO exclude_model

![Image](https://github.com/user-attachments/assets/ae58a1b7-e232-4fa8-805f-2d699fcdfeb0)

**Comment by 007revad** [comment]
What do these commands return?
```
synogetkeyvalue /etc/synoinfo.conf unique
synogetkeyvalue /etc.defaults/synoinfo.conf unique
```

**Comment by 007revad** [comment]
What do these commands return?
```
sudo readlink /var/packages/ContainerManager/etc
sudo readlink /var/packages/ContainerManager/home
sudo readlink /var/packages/ContainerManager/share
sudo readlink /var/packages/ContainerManager/target
sudo readlink /var/packages/ContainerManager/tmp
sudo readlink /var/packages/ContainerManager/var
```

**Comment by fvatter** [comment]
![Image](https://github.com/user-attachments/assets/98c3d50e-76ff-4f1c-8d30-b1978b12ce2a)

**Comment by 007revad** [comment]
@fvatter 
Everything looks normal.

Try uninstalling Container Manager then run the script to install it again.
