### ISSUE TITLE
Failed to check service status for ContainerManager

### ISSUE THREAD

**Issue by Papitomalote** [007revad/ContainerManager_for_all_armv8#32]
Hello, when I try to install Container Manger in windows powershell everything works until I select the volume where I want to install the app. This message shows up "Failed to check service status for ContainerManager" and I cannot do anything else. Any fix for this? DS418

Thanks!

**Comment by 007revad** [comment]
Can you reply with the full output of the script.

**Comment by Papitomalote** [comment]
Sorry, my bad, I forgot to update to DSM 7.2+ Everything works perfect, thanks!
