### ISSUE TITLE
Exited script during manual install - synoinfo.conf corrupt?

### ISSUE THREAD

**Issue by D4v3R4v3** [007revad/ContainerManager_for_all_armv8#33]
Hi there,
I tried installing the Container Manager manually on my Synology DS218 (DSM 7.2.2-72806 Update 2) but right before I was able to continue with the script, typing "yes", putty froze and I couldn't continue anymore and I had to quit eventually. I guess I now have my synoinfo.conf file corrupted or something like that because I see a lot of errors in my Package Center and also the OpenVPN server does not start up anmyore. Is there a way to get back to the backed-up file by the script? If yes, where is it stored and how can I substitute the modified one? I tried to restore my configuration file backup (*.dss) but that didn't work unfortunately.
Any help would be greatly appreciated!
Thank you!
David

**Comment by 007revad** [comment]
Give me minute and I'll provide the steps to recover.

**Comment by 007revad** [comment]
Run these 2 commands in putty.
```
sudo synosetkeyvalue /etc/synoinfo.conf unique synology_rtd1296_ds218
sudo synosetkeyvalue /etc.defaults/synoinfo.conf unique synology_rtd1296_ds218
```

**Comment by blackdwarf1945** [comment]
Hi, my last update 7.2.1-69057 Update 6 on DS218.
What to do?

![Screenshot_1177](https://github.com/user-attachments/assets/963ecf65-6ed7-466d-80a6-8b4c6b100b1b)

**Comment by 007revad** [comment]
@blackdwarf1945 

Did you manually install container manager when the script told you to?
In that step you should have downloaded [ContainerManager-armv8-20.10.23-1437.spk](https://global.synologydownload.com/download/Package/spk/ContainerManager/20.10.23-1437/ContainerManager-armv8-20.10.23-1437.spk)

You can do a manual DSM update to DSM 7.2.2
1. Download this file [DSM_DS218_72806.pat](https://global.synologydownload.com/download/DSM/release/7.2.2/72806/DSM_DS218_72806.pat) to your DS218.
2. Go to "Control Panel > Update & Restore"
3. Click on "Manual DSM Update" and browse to where you download the file to in step 1.

**Comment by D4v3R4v3** [comment]
@007revad thanks for the quick response. Unfortunately with my VPN not working I don't manage to ssh into my Synology at the moment because I'm coming back to the house where the server is located only in a week.
As soon as I manage I'll update you. In the meantime do you recommend to not restart the server or will it not change anything in that situation?

**Comment by blackdwarf1945** [comment]
> @blackdwarf1945 
> 
> Did you manually install container manager when the script told you to?
> In that step you should have downloaded [ContainerManager-armv8-20.10.23-1437.spk](https://global.synologydownload.com/download/Package/spk/ContainerManager/20.10.23-1437/ContainerManager-armv8-20.10.23-1437.spk)
> 
> You can do a manual DSM update to DSM 7.2.2
> 1. Download this file [DSM_DS218_72806.pat](https://global.synologydownload.com/download/DSM/release/7.2.2/72806/DSM_DS218_72806.pat) to your DS218.
> 2. Go to "Control Panel > Update & Restore"
> 3. Click on "Manual DSM Update" and browse to where you download the file to in step 1.

Thx, it works.

**Comment by 007revad** [comment]
@D4v3R4v3 

> @007revad thanks for the quick response. Unfortunately with my VPN not working I don't manage to ssh into my Synology at the moment because I'm coming back to the house where the server is located only in a week. As soon as I manage I'll update you. In the meantime do you recommend to not restart the server or will it not change anything in that situation?

Definitely do **NOT** reboot until you have fixed synoinfo.conf. I don't know would happen if it rebooted while synoinfo.conf says it's a DS418.

If anyone is at the house you should ask them to unplug the network cable... just in case Synology release a new DSM version or package updates before you get home.

**Comment by D4v3R4v3** [comment]
OK, I just disabled all automatic updates since there's nobody there to unplug the cable (quickconnect still works). Thanks for the hint!
In the meantime I'll try to find a way to install a terminal or something that works in the gui (even though it seems that since DSM 7.x there's nothing available anymore).

**Comment by 007revad** [comment]
As you can remotely access the DSM webui you can run the following commands via task scheduler. 

1. Create > Scheduled Task > User-defined script.
2. Set the User to root.
3. Untick Enabled.
4. Click on the "Task Settings" tab.
5. Under "User-defined script" paste:
```
/usr/syno/bin/synosetkeyvalue /etc/synoinfo.conf unique synology_rtd1296_ds218
/usr/syno/bin/synosetkeyvalue /etc.defaults/synoinfo.conf unique synology_rtd1296_ds218
```
6. Click OK.
7. Select this task and Click on the Run button.

After you've run the task you can click on "Action > View result" to see if the "Current status" was normal and if there were any errors.

**Comment by D4v3R4v3** [comment]
That was it! Thank you so much! Everything seems to be back to normal again! 
What do you suggest now to complete the installation of the ContainerManager? I've done everything including preventing it to auto-update ... in the package center I see an error for the Container Manager.

**Comment by 007revad** [comment]
You can delete the scheduled task you made now.
